export interface Cars {
  id: string;
  name: string;
  price: number;
  owned: boolean;
  maintainance: number;
  source: number; // Assuming 'source' is of type number (require statement)
}

export const carsData: Cars[] = [
  {
    id: "1",
    name: "Mercedes S-class Maybach",
    owned: false,
    price: 350000,
    maintainance: 10000,
    source: require("../assets/images/cars/merc.png"),
  },
  {
    id: "2",
    name: "Mclaren MCL38 F1 Car",
    owned: false,
    maintainance: 280000,
    price: 100000000,
    source: require("../assets/images/cars/image.png"),
  },
  {
    id: "3",
    name: "Mercedes W13 F1 Car",
    owned: false,
    maintainance: 320000,
    price: 280000000,
    source: require("../assets/images/cars/mercf12022.png"),
  },
  {
    id: "4",
    name: "Mclaren 765LT",
    owned: false,
    maintainance: 35000,
    price: 1000000,
    source: require("../assets/images/cars/mclaren.png"),
  },
  {
    id: "5",
    name: "Mercedes AMG GT",
    owned: false,
    maintainance: 40000,
    price: 350000,
    source: require("../assets/images/cars/amgGTblack.png"),
  },
  {
    id: "6",
    name: "Pagani Huayra R EVO",
    owned: false,
    maintainance: 125000,
    price: 4500000,
    source: require("../assets/images/cars/paganievo.png"),
  },
  {
    id: "7",
    name: "Bugatti Tourbillon",
    owned: false,
    maintainance: 175000,
    price: 5500000,
    source: require("../assets/images/cars/buggatiTourbillon.png"),
  },
  {
    id: "8",
    name: "Astorn Martin DB",
    owned: false,
    maintainance: 12000,
    price: 270000,
    source: require("../assets/images/cars/astonmartinggreen.png"),
  },
  {
    id: "9",
    name: "Mclaren Spider",
    owned: false,
    maintainance: 24000,
    price: 382500,
    source: require("../assets/images/cars/mclarenspyder.png"),
  },
  {
    id: "10",
    name: "Porsche Turbo",
    owned: false,
    maintainance: 16000,
    price: 250000,
    source: require("../assets/images/cars/porscheturbo.png"),
  },
  {
    id: "11",
    name: "Porsche Spyder",
    owned: false,
    maintainance: 20000,
    price: 260000,
    source: require("../assets/images/cars/porschespyder.png"),
  },
  {
    id: "12",
    name: "Bugatti Mistral",
    owned: false,
    maintainance: 155000,
    price: 5000000,
    source: require("../assets/images/cars/buggatiMistral.png"),
  },
  {
    id: "13",
    name: "Porsche 911",
    owned: false,
    maintainance: 26000,
    price: 187995,
    source: require("../assets/images/cars/porsche911.png"),
  },
  {
    id: "14",
    name: "Maserati MC 20",
    owned: false,
    maintainance: 9500,
    price: 235700,
    source: require("../assets/images/cars/maseratimc20.png"),
  },
  {
    id: "15",
    name: "Aston Martin Valhalla",
    owned: false,
    maintainance: 12500,
    price: 800000,
    source: require("../assets/images/cars/astonmartingvalhalla.png"),
  },
  {
    id: "16",
    name: "Mercedes Benz AMG GT Coupe",
    owned: false,
    maintainance: 5500,
    price: 135000,
    source: require("../assets/images/cars/amgGTCoupe.png"),
  },
  {
    id: "17",
    name: "Dodge SRT Hellcat",
    owned: false,
    maintainance: 2800,
    price: 107500,
    source: require("../assets/images/cars/dodgehellcat.png"),
  },
  {
    id: "18",
    name: "Lincoln Nautilus",
    owned: false,
    maintainance: 650,
    price: 76545,
    source: require("../assets/images/cars/lincolnnautilus.png"),
  },
  {
    id: "19",
    name: "Range Rover SV Autobiography",
    owned: false,
    maintainance: 2500,
    price: 184000,
    source: require("../assets/images/cars/rangeroverautobiography.png"),
  },
  {
    id: "20",
    name: "Mercedes AMG ONE",
    owned: false,
    maintainance: 69500,
    price: 4584000,
    source: require("../assets/images/cars/mercedesamgone.png"),
  },
  {
    id: "21",
    name: "Aston Martin Valkyrie AMR Pro",
    owned: false,
    maintainance: 185000,
    price: 4400000,
    source: require("../assets/images/cars/amrpro.png"),
  },
  {
    id: "22",
    name: "Koenigsegg Jesko",
    owned: false,
    maintainance: 175000,
    price: 3400000,
    source: require("../assets/images/cars/koenigseggjesko.png"),
  },
  {
    id: "23",
    name: "Bentley EXP 100 GT",
    owned: false,
    maintainance: 43250,
    price: 1900000,
    source: require("../assets/images/cars/bentleyexp100gt.png"),
  },
  {
    id: "24",
    name: "Porsche 918 Spyder",
    owned: false,
    maintainance: 36500,
    price: 2200000,
    source: require("../assets/images/cars/porsche918spyder.png"),
  },
  {
    id: "25",
    name: "Koenigsegg CC850",
    owned: false,
    maintainance: 39200,
    price: 3650000,
    source: require("../assets/images/cars/koenigseggcc850.png"),
  },
  {
    id: "26",
    name: "Mclaren 720s",
    owned: false,
    maintainance: 26000,
    price: 326000,
    source: require("../assets/images/cars/mclaren720s.png"),
  },
  {
    id: "27",
    name: "Pagani Huayra Tricolore",
    owned: false,
    maintainance: 85750,
    price: 7100000,
    source: require("../assets/images/cars/paganihuayratricolore.png"),
  },
  {
    id: "28",
    name: "Mercedes GLS",
    owned: false,
    maintainance: 1850,
    price: 150000,
    source: require("../assets/images/cars/mercedesgls.png"),
  },
  {
    id: "29",
    name: "Maserati GT2 Racecar",
    owned: false,
    maintainance: 68750,
    price: 525000,
    source: require("../assets/images/cars/maseratigt2.png"),
  },
  {
    id: "30",
    name: "Pagani Imola Roadster",
    owned: false,
    maintainance: 124750,
    price: 7525000,
    source: require("../assets/images/cars/paganiimola2021.png"),
  },
  {
    id: "31",
    name: "Mercedes S Class",
    owned: false,
    maintainance: 2200,
    price: 234300,
    source: require("../assets/images/cars/mercedessclass.png"),
  },
  {
    id: "32",
    name: "Pagani Utopia",
    owned: false,
    maintainance: 76750,
    price: 2500000,
    source: require("../assets/images/cars/paganiutopia.png"),
  },
  {
    id: "33",
    name: "Mercedes G Wagon",
    owned: false,
    maintainance: 1900,
    price: 170000,
    source: require("../assets/images/cars/gwagon.png"),
  },
  {
    id: "34",
    name: "Mercedes-Maybach GLS 600",
    owned: false,
    maintainance: 2950,
    price: 220500,
    source: require("../assets/images/cars/mercedesglsmaybach.png"),
  },
  {
    id: "35",
    name: "Bugatti Chiron Pur Sport",
    owned: false,
    maintainance: 145500,
    price: 4100000,
    source: require("../assets/images/cars/bugattishironpursport.png"),
  },
  {
    id: "36",
    name: "Bugatti Centodieci",
    owned: false,
    maintainance: 225000,
    price: 9000000,
    source: require("../assets/images/cars/bugatticentodieci.png"),
  },
];
