export interface Property {
  id: string;
  price: number;
  owned: boolean;
  rentalIncome: number;
  location: string;
  source: number; // Assuming 'source' is of type number (require statement)
}

// export const propertyData: Property[] = [
//   {
//     id: "1",
//     income: 12000,
//     price: 28000000,
//     location: "Alpine, USA",
//     source: require("../assets/buildings/alpine.png"),
//   },
//   {
//     id: "2",
//     income: 12000,
//     price: 28000000,
//     location: "California, USA",
//     source: require("../assets/buildings/california.jpg"),
//   },
//   {
//     id: "3",
//     income: 12000,
//     price: 28000000,
//     location: "Cape Town, South Africa",
//     source: require("../assets/buildings/capetown.jpg"),
//   },
//   {
//     id: "4",
//     income: 12000,
//     price: 28000000,
//     location: "Chicago, USA",
//     source: require("../assets/buildings/chicago.jpg"),
//   },
//   {
//     id: "5",
//     income: 12000,
//     price: 28000000,
//     location: "Chicago, USA",
//     source: require("../assets/buildings/chicago2.jpg"),
//   },
//   {
//     id: "6",
//     income: 12000,
//     price: 28000000,
//     location: "Chicago, USA",
//     source: require("../assets/buildings/chicago3.jpg"),
//   },
//   {
//     id: "7",
//     income: 12000,
//     price: 28000000,
//     location: "Cyprus",
//     source: require("../assets/buildings/cyprus.jpg"),
//   },
//   {
//     id: "8",
//     income: 12000,
//     price: 28000000,
//     location: "Dubai, UAE",
//     source: require("../assets/buildings/dubai.jpg"),
//   },
//   {
//     id: "9",
//     income: 12000,
//     price: 28000000,
//     location: "Hong Kong",
//     source: require("../assets/buildings/hongkong.jpg"),
//   },
//   {
//     id: "10",
//     income: 12000,
//     price: 28000000,
//     location: "London, UK",
//     source: require("../assets/buildings/london.jpg"),
//   },
//   {
//     id: "11",
//     income: 12000,
//     price: 28000000,
//     location: "London, UK",
//     source: require("../assets/buildings/londontwo.jpg"),
//   },
//   {
//     id: "12",
//     income: 12000,
//     price: 28000000,
//     location: "Malaysia",
//     source: require("../assets/buildings/malasiya.jpg"),
//   },
//   {
//     id: "13",
//     income: 12000,
//     price: 28000000,
//     location: "Shenzhen, China",
//     source: require("../assets/buildings/shenzhen.jpg"),
//   },
// ];

export const personalPropertyData: Property[] = [
  {
    id: "1",
    owned: false,
    price: 28000000,
    rentalIncome: 120000,
    location: "Alpine, USA",
    source: require("../assets/buildings/alpine.png"),
  },
  {
    id: "2",
    owned: false,
    rentalIncome: 122000,
    price: 300000000,
    location: "California, USA",
    source: require("../assets/buildings/california.jpg"),
  },
  {
    id: "3",
    owned: false,
    rentalIncome: 112000,
    price: 280000000,
    location: "Cape Town, South Africa",
    source: require("../assets/buildings/capetown.jpg"),
  },
  {
    id: "4",
    owned: false,
    rentalIncome: 132000,
    price: 600000000,
    location: "Chicago, USA",
    source: require("../assets/buildings/chicago.jpg"),
  },
  {
    id: "5",
    owned: false,
    rentalIncome: 142000,
    price: 850000000,
    location: "Chicago, USA",
    source: require("../assets/buildings/chicago2.jpg"),
  },
  {
    id: "6",
    owned: false,
    rentalIncome: 152000,
    price: 1000000000,
    location: "Chicago, USA",
    source: require("../assets/buildings/chicago3.jpg"),
  },
  {
    id: "7",
    owned: false,
    rentalIncome: 121000,
    price: 1200000000,
    location: "Cyprus",
    source: require("../assets/buildings/cyprus.jpg"),
  },
  {
    id: "8",
    owned: false,
    rentalIncome: 122000,
    price: 5750000000,
    location: "Dubai, UAE",
    source: require("../assets/buildings/dubai.jpg"),
  },
  {
    id: "9",
    owned: false,
    rentalIncome: 120200,
    price: 6200000000,
    location: "Hong Kong",
    source: require("../assets/buildings/hongkong.jpg"),
  },
  {
    id: "10",
    owned: false,
    rentalIncome: 12000,
    price: 6600000000,
    location: "London, UK",
    source: require("../assets/buildings/london.jpg"),
  },
  {
    id: "11",
    owned: false,
    rentalIncome: 1202400,
    price: 7000000000,
    location: "London, UK",
    source: require("../assets/buildings/londontwo.jpg"),
  },
  {
    id: "12",
    owned: false,
    rentalIncome: 1201200,
    price: 7600000000,
    location: "Malaysia",
    source: require("../assets/buildings/malasiya.jpg"),
  },
  {
    id: "13",
    owned: false,
    rentalIncome: 120300,
    price: 8000000000,
    location: "Shenzhen, China",
    source: require("../assets/buildings/shenzhen.jpg"),
  },
];
