export interface Property {
  id: string;
  price: number;
  owned: boolean;
  rentalIncome: number;
  maintainance: number;
  location: string;
  source: number; // Assuming 'source' is of type number (require statement)
}

// export const propertyData: Property[] = [
//   {
//     id: "1",
//     income: 12000,
//     price: 28000000,
//     location: "Alpine, USA",
//     source: require("../assets/buildings/alpine.png"),
//   },
//   {
//     id: "2",
//     income: 12000,
//     price: 28000000,
//     location: "California, USA",
//     source: require("../assets/buildings/california.jpg"),
//   },
//   {
//     id: "3",
//     income: 12000,
//     price: 28000000,
//     location: "Cape Town, South Africa",
//     source: require("../assets/buildings/capetown.jpg"),
//   },
//   {
//     id: "4",
//     income: 12000,
//     price: 28000000,
//     location: "Chicago, USA",
//     source: require("../assets/buildings/chicago.jpg"),
//   },
//   {
//     id: "5",
//     income: 12000,
//     price: 28000000,
//     location: "Chicago, USA",
//     source: require("../assets/buildings/chicago2.jpg"),
//   },
//   {
//     id: "6",
//     income: 12000,
//     price: 28000000,
//     location: "Chicago, USA",
//     source: require("../assets/buildings/chicago3.jpg"),
//   },
//   {
//     id: "7",
//     income: 12000,
//     price: 28000000,
//     location: "Cyprus",
//     source: require("../assets/buildings/cyprus.jpg"),
//   },
//   {
//     id: "8",
//     income: 12000,
//     price: 28000000,
//     location: "Dubai, UAE",
//     source: require("../assets/buildings/dubai.jpg"),
//   },
//   {
//     id: "9",
//     income: 12000,
//     price: 28000000,
//     location: "Hong Kong",
//     source: require("../assets/buildings/hongkong.jpg"),
//   },
//   {
//     id: "10",
//     income: 12000,
//     price: 28000000,
//     location: "London, UK",
//     source: require("../assets/buildings/london.jpg"),
//   },
//   {
//     id: "11",
//     income: 12000,
//     price: 28000000,
//     location: "London, UK",
//     source: require("../assets/buildings/londontwo.jpg"),
//   },
//   {
//     id: "12",
//     income: 12000,
//     price: 28000000,
//     location: "Malaysia",
//     source: require("../assets/buildings/malasiya.jpg"),
//   },
//   {
//     id: "13",
//     income: 12000,
//     price: 28000000,
//     location: "Shenzhen, China",
//     source: require("../assets/buildings/shenzhen.jpg"),
//   },
// ];

export const personalPropertyData: Property[] = [
  {
    id: "1",
    owned: false,
    price: 28000000,
    rentalIncome: 65000,
    maintainance: 35500,
    location: "Alpine, USA",
    source: require("../assets/buildings/alpine.png"),
  },
  {
    id: "2",
    owned: false,
    rentalIncome: 1450000,
    maintainance: 452000,
    price: 2650000000,
    location: "California, USA",
    source: require("../assets/buildings/california.jpg"),
  },
  {
    id: "3",
    owned: false,
    rentalIncome: 1750000,
    maintainance: 625000,
    price: 290000000,
    location: "Cape Town, South Africa",
    source: require("../assets/buildings/capetown.jpg"),
  },
  {
    id: "4",
    owned: false,
    rentalIncome: 4950000,
    maintainance: 1450000,
    price: 600000000,
    location: "Chicago, USA",
    source: require("../assets/buildings/chicago.jpg"),
  },
  {
    id: "5",
    owned: false,
    rentalIncome: 6520000,
    maintainance: 1900000,
    price: 850000000,
    location: "Chicago, USA",
    source: require("../assets/buildings/chicago2.jpg"),
  },
  {
    id: "6",
    owned: false,
    rentalIncome: 9200000,
    maintainance: 2650000,
    price: 1000000000,
    location: "Chicago, USA",
    source: require("../assets/buildings/chicago3.jpg"),
  },
  {
    id: "7",
    owned: false,
    rentalIncome: 10000000,
    maintainance: 3600000,
    price: 1200000000,
    location: "Cyprus",
    source: require("../assets/buildings/cyprus.jpg"),
  },
  {
    id: "8",
    owned: false,
    rentalIncome: 12000000,
    maintainance: 4100000,
    price: 5250000000,
    location: "Dubai, UAE",
    source: require("../assets/buildings/dubai.jpg"),
  },
  {
    id: "9",
    owned: false,
    rentalIncome: 13500000,
    maintainance: 4900000,
    price: 5900000000,
    location: "Hong Kong",
    source: require("../assets/buildings/hongkong.jpg"),
  },
  {
    id: "10",
    owned: false,
    rentalIncome: 14500000,
    maintainance: 5200000,
    price: 6400000000,
    location: "London, UK",
    source: require("../assets/buildings/london.jpg"),
  },
  {
    id: "11",
    owned: false,
    rentalIncome: 17000000,
    maintainance: 6000000,
    price: 7000000000,
    location: "London, UK",
    source: require("../assets/buildings/londontwo.jpg"),
  },
  {
    id: "12",
    owned: false,
    rentalIncome: 21000000,
    maintainance: 8000000,
    price: 7600000000,
    location: "Malaysia",
    source: require("../assets/buildings/malasiya.jpg"),
  },
  {
    id: "13",
    owned: false,
    rentalIncome: 25000000,
    maintainance: 9500000,
    price: 8000000000,
    location: "Shenzhen, China",
    source: require("../assets/buildings/shenzhen.jpg"),
  },
];
